import {
  AccountIcon,
  AccountMenuIcon,
  AddIcon,
  ArrowLeftIcon,
  BellIcon,
  CartIcon,
  CartMenuIcon,
  CategoriesMenuIcon,
  CheckCircleOutlineIcon,
  CheckedCircle,
  CheckedCircleOutlineBigIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CloseCircleOutlineIcon,
  CloseIcon,
  CopyIcon,
  CopyLink,
  CreditCardIcon,
  CreditScoreIcon,
  DeliveryBoxIcon,
  DistanceIcon,
  EditIcon,
  EmailFastIcon,
  EmailIcon,
  FaceIdIcon,
  Fb,
  FilterIcon,
  HandPhoneIcon,
  HomeIcon,
  Ig,
  InfoCircleIcon,
  LanguageIcon,
  Line,
  LinkIcon,
  LocalShippingIcon,
  LogoutIcon,
  MenuIcon,
  MoreIcon,
  OrderDollarIcon,
  OrderIcon,
  PanZoomIcon,
  PhoneChatIcon,
  PlayIcon,
  SearchActivityIcon,
  SearchIcon,
  ShareIcon,
  SortIcon,
  SoundOffIcon,
  SoundOnIcon,
  SubstractIcon,
  Telegram,
  TimeIcon,
  TrashBinOutline,
  TrashBinOutline2,
  TrashIcon,
  VerifiedUserIcon,
  VoucherBigIcon,
  Whatsapp,
  WishlistIcon,
  WishlistOutlineIcon
} from 'assets/icons';
import React from 'react';
import { SvgProps } from 'react-native-svg';
import colors from 'styles/colors';

import { IconProps, IconType } from './icon.type';

export const Icon = ({ name, fill, color, size, stroke }: IconProps) => {
  const svgFillIconProps: SvgProps = {
    fill: fill || colors.dark.gumbo,
    color: color || colors.dark.gumbo,
    stroke: stroke || '',
    height: size || '24px',
    width: size || '24px'
  };

  //FIX: Uncomment if need stroke icon style
  // const svgStrokeIconProps: SvgProps = {
  //   stroke: color || colors.dark.gumbo,
  //   height: size || '24px',
  //   width: size || '24px'
  // };

  const iconName: Record<IconType, JSX.Element> = {
    account: <AccountIcon {...svgFillIconProps} />,
    accountMenu: <AccountMenuIcon {...svgFillIconProps} />,
    cart: <CartIcon {...svgFillIconProps} />,
    cartMenu: <CartMenuIcon {...svgFillIconProps} />,
    categoriesMenu: <CategoriesMenuIcon {...svgFillIconProps} />,
    checkCircleOutline: <CheckCircleOutlineIcon {...svgFillIconProps} />,
    checkedCircleOutlineBig: <CheckedCircleOutlineBigIcon {...svgFillIconProps} />,
    chevronRight: <ChevronRightIcon {...svgFillIconProps} />,
    chevronLeft: <ChevronLeftIcon {...svgFillIconProps} />,
    closeCircleOutline: <CloseCircleOutlineIcon {...svgFillIconProps} />,
    distance: <DistanceIcon {...svgFillIconProps} />,
    edit: <EditIcon {...svgFillIconProps} />,
    email: <EmailIcon {...svgFillIconProps} />,
    emailFast: <EmailFastIcon {...svgFillIconProps} />,
    faceId: <FaceIdIcon {...svgFillIconProps} />,
    handPhone: <HandPhoneIcon {...svgFillIconProps} />,
    home: <HomeIcon {...svgFillIconProps} />,
    infoCircle: <InfoCircleIcon {...svgFillIconProps} />,
    language: <LanguageIcon {...svgFillIconProps} />,
    link: <LinkIcon {...svgFillIconProps} />,
    logout: <LogoutIcon {...svgFillIconProps} />,
    menu: <MenuIcon {...svgFillIconProps} />,
    more: <MoreIcon {...svgFillIconProps} />,
    order: <OrderIcon {...svgFillIconProps} />,
    orderDollar: <OrderDollarIcon {...svgFillIconProps} />,
    phoneChat: <PhoneChatIcon {...svgFillIconProps} />,
    arrowLeft: <ArrowLeftIcon {...svgFillIconProps} />,
    search: <SearchIcon {...svgFillIconProps} />,
    add: <AddIcon {...svgFillIconProps} />,
    substract: <SubstractIcon {...svgFillIconProps} />,
    panZoom: <PanZoomIcon {...svgFillIconProps} />,
    trash: <TrashIcon {...svgFillIconProps} />,
    bell: <BellIcon {...svgFillIconProps} />,
    chevronDown: <ChevronDownIcon {...svgFillIconProps} />,
    copy: <CopyIcon {...svgFillIconProps} />,
    deliveryBox: <DeliveryBoxIcon {...svgFillIconProps} />,
    verifiedUser: <VerifiedUserIcon {...svgFillIconProps} />,
    time: <TimeIcon {...svgFillIconProps} />,
    creditCard: <CreditCardIcon {...svgFillIconProps} />,
    creditScore: <CreditScoreIcon {...svgFillIconProps} />,
    localShipping: <LocalShippingIcon {...svgFillIconProps} />,
    checkedCircle: <CheckedCircle {...svgFillIconProps} />,
    close: <CloseIcon {...svgFillIconProps} />,
    searchActivity: <SearchActivityIcon {...svgFillIconProps} />,
    sortIcon: <SortIcon {...svgFillIconProps} />,
    filterIcon: <FilterIcon {...svgFillIconProps} />,
    trashBinOutline: <TrashBinOutline {...svgFillIconProps} />,
    trashBinOutline2: <TrashBinOutline2 {...svgFillIconProps} />,
    voucherBig: <VoucherBigIcon {...svgFillIconProps} />,
    wishlist: <WishlistIcon {...svgFillIconProps} />,
    wishlistOutline: <WishlistOutlineIcon {...svgFillIconProps} />,
    play: <PlayIcon {...svgFillIconProps} />,
    soundOff: <SoundOffIcon {...svgFillIconProps} />,
    soundOn: <SoundOnIcon {...svgFillIconProps} />,
    shareIcon: <ShareIcon {...svgFillIconProps} />,
    fb: <Fb {...svgFillIconProps} />,
    instagram: <Ig {...svgFillIconProps} />,
    line: <Line {...svgFillIconProps} />,
    telegram: <Telegram {...svgFillIconProps} />,
    whatsapp: <Whatsapp {...svgFillIconProps} />,
    copyLink: <CopyLink {...svgFillIconProps} />
  };

  return iconName[name];
};
